export const users = [
    {
      "id": 1,
      "name": "Leanne Graham",
      "username": "Bret",
      "email": "Sincere@april.biz",
      "status" : "On Hold",
      "address": {
        "street": "Kulas Light",
        "suite": "Apt. 556",
        "city": "Gwenborough",
        "zipcode": "92998-3874",
        "geo": {
          "lat": "-37.3159",
          "lng": "81.1496"
        }
      },
      "phone": "1-770-736-8031 x56442",
      "website": "hildegard.org",
      "company": {
        "name": "Romaguera-Crona",
        "catchPhrase": "Multi-layered client-server neural-net",
        "bs": "harness real-time e-markets"
      }
    },
    {
      "id": 2,
      "name": "Ervin Howell",
      "username": "Antonette",
      "email": "Shanna@melissa.tv",
      "status" : "Processing",
      "address": {
        "street": "Victor Plains",
        "suite": "Suite 879",
        "city": "Wisokyburgh",
        "zipcode": "90566-7771",
        "geo": {
          "lat": "-43.9509",
          "lng": "-34.4618"
        }
      },
      "phone": "010-692-6593 x09125",
      "website": "anastasia.net",
      "company": {
        "name": "Deckow-Crist",
        "catchPhrase": "Proactive didactic contingency",
        "bs": "synergize scalable supply-chains"
      }
    },
    {
      "id": 3,
      "name": "Clementine Bauch",
      "username": "Samantha",
      "email": "Nathan@yesenia.net",
      "status" : "Completed",
      "address": {
        "street": "Douglas Extension",
        "suite": "Suite 847",
        "city": "McKenziehaven",
        "zipcode": "59590-4157",
        "geo": {
          "lat": "-68.6102",
          "lng": "-47.0653"
        }
      },
      "phone": "1-463-123-4447",
      "website": "ramiro.info",
      "company": {
        "name": "Romaguera-Jacobson",
        "catchPhrase": "Face to face bifurcated interface",
        "bs": "e-enable strategic applications"
      }
    },
    {
      "id": 4,
      "name": "Patricia Lebsack",
      "username": "Karianne",
      "email": "Julianne.OConner@kory.org",
      "status" : "Processing",
      "address": {
        "street": "Hoeger Mall",
        "suite": "Apt. 692",
        "city": "South Elvis",
        "zipcode": "53919-4257",
        "geo": {
          "lat": "29.4572",
          "lng": "-164.2990"
        }
      },
      "phone": "493-170-9623 x156",
      "website": "kale.biz",
      "company": {
        "name": "Robel-Corkery",
        "catchPhrase": "Multi-tiered zero tolerance productivity",
        "bs": "transition cutting-edge web services"
      }
    },
    {
      "id": 5,
      "name": "Chelsey Dietrich",
      "username": "Kamren",
      "email": "Lucio_Hettinger@annie.ca",
      "status" : "On Hold",
      "address": {
        "street": "Skiles Walks",
        "suite": "Suite 351",
        "city": "Roscoeview",
        "zipcode": "33263",
        "geo": {
          "lat": "-31.8129",
          "lng": "62.5342"
        }
      },
      "phone": "(254)954-1289",
      "website": "demarco.info",
      "company": {
        "name": "Keebler LLC",
        "catchPhrase": "User-centric fault-tolerant solution",
        "bs": "revolutionize end-to-end systems"
      }
    },
    {
      "id": 6,
      "name": "Mrs. Dennis Schulist",
      "username": "Leopoldo_Corkery",
      "email": "Karley_Dach@jasper.info",
      "status" : "Completed",
      "address": {
        "street": "Norberto Crossing",
        "suite": "Apt. 950",
        "city": "South Christy",
        "zipcode": "23505-1337",
        "geo": {
          "lat": "-71.4197",
          "lng": "71.7478"
        }
      },
      "phone": "1-477-935-8478 x6430",
      "website": "ola.org",
      "company": {
        "name": "Considine-Lockman",
        "catchPhrase": "Synchronised bottom-line interface",
        "bs": "e-enable innovative applications"
      }
    },
    {
      "id": 7,
      "name": "Kurtis Weissnat",
      "username": "Elwyn.Skiles",
      "email": "Telly.Hoeger@billy.biz",
      "status" : "Completed",
      "address": {
        "street": "Rex Trail",
        "suite": "Suite 280",
        "city": "Howemouth",
        "zipcode": "58804-1099",
        "geo": {
          "lat": "24.8918",
          "lng": "21.8984"
        }
      },
      "phone": "210.067.6132",
      "website": "elvis.io",
      "company": {
        "name": "Johns Group",
        "catchPhrase": "Configurable multimedia task-force",
        "bs": "generate enterprise e-tailers"
      }
    },
    {
      "id": 8,
      "name": "Nicholas Runolfsdottir V",
      "username": "Maxime_Nienow",
      "email": "Sherwood@rosamond.me",
      "status" : "Completed",
      "address": {
        "street": "Ellsworth Summit",
        "suite": "Suite 729",
        "city": "Aliyaview",
        "zipcode": "45169",
        "geo": {
          "lat": "-14.3990",
          "lng": "-120.7677"
        }
      },
      "phone": "586.493.6943 x140",
      "website": "jacynthe.com",
      "company": {
        "name": "Abernathy Group",
        "catchPhrase": "Implemented secondary concept",
        "bs": "e-enable extensible e-tailers"
      }
    },
    {
      "id": 9,
      "name": "Glenna Reichert",
      "username": "Delphine",
      "email": "Chaim_McDermott@dana.io",
      "status" : "On Hold",
      "address": {
        "street": "Dayna Park",
        "suite": "Suite 449",
        "city": "Bartholomebury",
        "zipcode": "76495-3109",
        "geo": {
          "lat": "24.6463",
          "lng": "-168.8889"
        }
      },
      "phone": "(775)976-6794 x41206",
      "website": "conrad.com",
      "company": {
        "name": "Yost and Sons",
        "catchPhrase": "Switchable contextually-based project",
        "bs": "aggregate real-time technologies"
      }
    },
    {
      "id": 10,
      "name": "Clementina DuBuque",
      "username": "Moriah.Stanton",
      "email": "Rey.Padberg@karina.biz",
      "status" : "Processing",
      "address": {
        "street": "Kattie Turnpike",
        "suite": "Suite 198",
        "city": "Lebsackbury",
        "zipcode": "31428-2261",
        "geo": {
          "lat": "-38.2386",
          "lng": "57.2232"
        }
      },
      "phone": "024-648-3804",
      "website": "ambrose.net",
      "company": {
        "name": "Hoeger LLC",
        "catchPhrase": "Centralized empowering task-force",
        "bs": "target end-to-end models"
      }
    }
  ]

export const comments = [
    {
      "postId": 1,
      "id": 1,
      "name": "id labore ex et quam laborum",
      "email": "Eliseo@gardner.biz",
      "body": "laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium"
    },
    {
      "postId": 1,
      "id": 2,
      "name": "quo vero reiciendis velit similique earum",
      "email": "Jayne_Kuhic@sydney.com",
      "body": "est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et"
    },
    {
      "postId": 1,
      "id": 3,
      "name": "odio adipisci rerum aut animi",
      "email": "Nikita@garfield.biz",
      "body": "quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione"
    },
    {
      "postId": 1,
      "id": 4,
      "name": "alias odio sit",
      "email": "Lew@alysha.tv",
      "body": "non et atque\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\nquia voluptas consequuntur itaque dolor\net qui rerum deleniti ut occaecati"
    },
    {
      "postId": 1,
      "id": 5,
      "name": "vero eaque aliquid doloribus et culpa",
      "email": "Hayden@althea.biz",
      "body": "harum non quasi et ratione\ntempore iure ex voluptates in ratione\nharum architecto fugit inventore cupiditate\nvoluptates magni quo et"
    }
  ]

  // https://www.chatgpters.org/c/aitalk/chat-gpt-w-r
  export const promptOptions = [
    { value: 'a2', label: 'A2', prompt: 'Write a [A2] level essay with the title \n\n:'},
    { value: 'b2', label: 'B2', prompt: 'Write a [B2] level essay with the title \n\n:'},
    { value: 'c2', label: 'C2', prompt: 'Write a [C2] level essay with the title \n\n:' },
    { value: 'blog', label: 'Blog', prompt: 'Write a blog post with the title \n\n:'},
    { value: 'essay', label: 'TOEFL Essay', prompt: 'Write a TOEFL essay with the title \n\n:' },
    { value: '개요작성', label: '개요작성', prompt: 'Generate a list of candidate essay topics below, and write a brief outline of the main points to be discussed. \n\n:' },
    { value: 'College Class Poem', label: '대학입문 시 작성', prompt: 'For an introductory college class, write a poem on the topic below. \n\n:' },
    { value: '5세 에세이', label: '5세 에세이', prompt: 'Write a detailed essay on the topic below, adding all the information you need. Write your essay using simple English, as if you were explaining something to a 5-year-old. \n\nTopic:' },
  ];
  

  // export const flavourOptions: readonly FlavourOption[] = [
  //   { value: 'vanilla', label: 'Vanilla', rating: 'safe' },
  //   { value: 'chocolate', label: 'Chocolate', rating: 'good' },
  //   { value: 'strawberry', label: 'Strawberry', rating: 'wild' },
  //   { value: 'salted-caramel', label: 'Salted Caramel', rating: 'crazy' },
  // ];
  

  // export const stateOptions: readonly StateOption[] = [
  //   { value: 'AL', label: 'Alabama' },
  //   { value: 'AK', label: 'Alaska' },
  //   { value: 'AS', label: 'American Samoa' },
  //   { value: 'AZ', label: 'Arizona' },
  //   { value: 'AR', label: 'Arkansas' },
  //   { value: 'CA', label: 'California' },
  //   { value: 'CO', label: 'Colorado' },
  //   { value: 'CT', label: 'Connecticut' },
  //   { value: 'DE', label: 'Delaware' },
  //   { value: 'DC', label: 'District Of Columbia' },
  //   { value: 'FM', label: 'Federated States Of Micronesia' },
  //   { value: 'FL', label: 'Florida' },
  //   { value: 'GA', label: 'Georgia' },
  //   { value: 'GU', label: 'Guam' },
  //   { value: 'HI', label: 'Hawaii' },
  //   { value: 'ID', label: 'Idaho' },
  //   { value: 'IL', label: 'Illinois' },
  //   { value: 'IN', label: 'Indiana' },
  //   { value: 'IA', label: 'Iowa' },
  //   { value: 'KS', label: 'Kansas' },
  //   { value: 'KY', label: 'Kentucky' },
  //   { value: 'LA', label: 'Louisiana' },
  //   { value: 'ME', label: 'Maine' },
  //   { value: 'MH', label: 'Marshall Islands' },
  //   { value: 'MD', label: 'Maryland' },
  //   { value: 'MA', label: 'Massachusetts' },
  //   { value: 'MI', label: 'Michigan' },
  //   { value: 'MN', label: 'Minnesota' },
  //   { value: 'MS', label: 'Mississippi' },
  //   { value: 'MO', label: 'Missouri' },
  //   { value: 'MT', label: 'Montana' },
  //   { value: 'NE', label: 'Nebraska' },
  //   { value: 'NV', label: 'Nevada' },
  //   { value: 'NH', label: 'New Hampshire' },
  //   { value: 'NJ', label: 'New Jersey' },
  //   { value: 'NM', label: 'New Mexico' },
  //   { value: 'NY', label: 'New York' },
  //   { value: 'NC', label: 'North Carolina' },
  //   { value: 'ND', label: 'North Dakota' },
  //   { value: 'MP', label: 'Northern Mariana Islands' },
  //   { value: 'OH', label: 'Ohio' },
  //   { value: 'OK', label: 'Oklahoma' },
  //   { value: 'OR', label: 'Oregon' },
  //   { value: 'PW', label: 'Palau' },
  //   { value: 'PA', label: 'Pennsylvania' },
  //   { value: 'PR', label: 'Puerto Rico' },
  //   { value: 'RI', label: 'Rhode Island' },
  //   { value: 'SC', label: 'South Carolina' },
  //   { value: 'SD', label: 'South Dakota' },
  //   { value: 'TN', label: 'Tennessee' },
  //   { value: 'TX', label: 'Texas' },
  //   { value: 'UT', label: 'Utah' },
  //   { value: 'VT', label: 'Vermont' },
  //   { value: 'VI', label: 'Virgin Islands' },
  //   { value: 'VA', label: 'Virginia' },
  //   { value: 'WA', label: 'Washington' },
  //   { value: 'WV', label: 'West Virginia' },
  //   { value: 'WI', label: 'Wisconsin' },
  //   { value: 'WY', label: 'Wyoming' },
  // ];
  
  // export const optionLength = [
  //   { value: 1, label: 'general' },
  //   {
  //     value: 2,
  //     label:
  //       'Evil is the moment when I lack the strength to be true to the Good that compels me.',
  //   },
  //   {
  //     value: 3,
  //     label:
  //       "It is now an easy matter to spell out the ethic of a truth: 'Do all that you can to persevere in that which exceeds your perseverance. Persevere in the interruption. Seize in your being that which has seized and broken you.",
  //   },
  // ];
  
  // export const dogOptions = [
  //   { id: 1, label: 'Chihuahua' },
  //   { id: 2, label: 'Bulldog' },
  //   { id: 3, label: 'Dachshund' },
  //   { id: 4, label: 'Akita' },
  // ];  

export const stopWords = [
"…",
"|",
"-",
"--",
"/",
"2023",
"à",
"a",
"e",
"&",
"w",
"o",
"—",
"się",
"de",
"en",
"la",
"il",
"le",
"di",
"da",
"about",
"above",
"after",
"again",
"against",
"all",
"am",
"an",
"and",
"any",
"are",
"aren't",
"as",
"at",
"be",
"because",
"been",
"before",
"being",
"below",
"between",
"both",
"but",
"by",
"can't",
"cannot",
"could",
"couldn't",
"did",
"didn't",
"do",
"does",
"doesn't",
"doing",
"don't",
"down",
"during",
"each",
"few",
"for",
"from",
"further",
"had",
"hadn't",
"has",
"hasn't",
"have",
"haven't",
"having",
"he",
"he'd",
"he'll",
"he's",
"her",
"here",
"here's",
"hers",
"herself",
"him",
"himself",
"his",
"how",
"how's",
"i",
"i'd",
"i'll",
"i'm",
"i've",
"if",
"in",
"into",
"is",
"isn't",
"it",
"it's",
"its",
"itself",
"let's",
"me",
"more",
"most",
"mustn't",
"my",
"myself",
"no",
"nor",
"not",
"of",
"off",
"on",
"once",
"only",
"or",
"other",
"ought",
"our",
"ours",
"ourselves",
"out",
"over",
"own",
"same",
"shan't",
"she",
"she'd",
"she'll",
"she's",
"should",
"shouldn't",
"so",
"some",
"such",
"than",
"that",
"that's",
"the",
"their",
"theirs",
"them",
"themselves",
"then",
"there",
"there's",
"these",
"they",
"they'd",
"they'll",
"they're",
"they've",
"this",
"those",
"through",
"to",
"too",
"under",
"until",
"up",
"very",
"was",
"wasn't",
"we",
"we'd",
"we'll",
"we're",
"we've",
"were",
"weren't",
"what",
"what's",
"when",
"when's",
"where",
"where's",
"which",
"while",
"who",
"who's",
"whom",
"why",
"why's",
"with",
"won't",
"would",
"wouldn't",
"you",
"you'd",
"you'll",
"you're",
"you've",
"your",
"yours",
"yourself",
"yourselves",
"a's",
"accordingly",
"again",
"allows",
"also",
"amongst",
"anybody",
"anyways",
"appropriate",
"aside",
"available",
"because",
"before",
"below",
"between",
"by",
"can't",
"certain",
"com",
"consider",
"corresponding",
"definitely",
"different",
"don't",
"each",
"else",
"et",
"everybody",
"exactly",
"fifth",
"follows",
"four",
"gets",
"goes",
"greetings",
"has",
"he",
"her",
"herein",
"him",
"how",
"i'm",
"immediate",
"indicate",
"instead",
"it",
"itself",
"know",
"later",
"lest",
"likely",
"ltd",
"me",
"more",
"must",
"nd",
"needs",
"next",
"none",
"nothing",
"of",
"okay",
"ones",
"others",
"ourselves",
"own",
"placed",
"probably",
"rather",
"regarding",
"right",
"saying",
"seeing",
"seen",
"serious",
"she",
"so",
"something",
"soon",
"still",
"t's",
"th",
"that",
"theirs",
"there",
"therein",
"they'd",
"third",
"though",
"thus",
"toward",
"try",
"under",
"unto",
"used",
"value",
"vs",
"way",
"we've",
"weren't",
"whence",
"whereas",
"whether",
"who's",
"why",
"within",
"wouldn't",
"you'll",
"yourself",
"able",
"across",
"against",
"almost",
"although",
"an",
"anyhow",
"anywhere",
"are",
"ask",
"away",
"become",
"beforehand",
"beside",
"beyond",
"c'mon",
"cannot",
"certainly",
"come",
"considering",
"could",
"described",
"do",
"done",
"edu",
"elsewhere",
"etc",
"everyone",
"example",
"first",
"for",
"from",
"getting",
"going",
"had",
"hasn't",
"he's",
"here",
"hereupon",
"himself",
"howbeit",
"i've",
"in",
"indicated",
"into",
"it'd",
"just",
"known",
"latter",
"let",
"little",
"mainly",
"mean",
"moreover",
"my",
"near",
"neither",
"nine",
"noone",
"novel",
"off",
"old",
"only",
"otherwise",
"out",
"particular",
"please",
"provides",
"rd",
"regardless",
"said",
"says",
"seem",
"self",
"seriously",
"should",
"some",
"sometime",
"sorry",
"sub",
"take",
"than",
"that's",
"them",
"there's",
"theres",
"they'll",
"this",
"three",
"to",
"towards",
"trying",
"unfortunately",
"up",
"useful",
"various",
"want",
"we",
"welcome",
"what",
"whenever",
"whereby",
"which",
"whoever",
"will",
"without",
"yes",
"you're",
"yourselves",
"about",
"actually",
"ain't",
"alone",
"always",
"and",
"anyone",
"apart",
"aren't",
"asking",
"awfully",
"becomes",
"behind",
"besides",
"both",
"c's",
"cant",
"changes",
"comes",
"contain",
"couldn't",
"despite",
"does",
"down",
"eg",
"enough",
"even",
"everything",
"except",
"five",
"former",
"further",
"given",
"gone",
"hadn't",
"have",
"hello",
"here's",
"hers",
"his",
"however",
"ie",
"inasmuch",
"indicates",
"inward",
"it'll",
"keep",
"knows",
"latterly",
"let's",
"look",
"many",
"meanwhile",
"most",
"myself",
"nearly",
"never",
"no",
"nor",
"now",
"often",
"on",
"onto",
"ought",
"outside",
"particularly",
"plus",
"que",
"re",
"regards",
"same",
"second",
"seemed",
"selves",
"seven",
"shouldn't",
"somebody",
"sometimes",
"specified",
"such",
"taken",
"thank",
"thats",
"themselves",
"thereafter",
"thereupon",
"they're",
"thorough",
"through",
"together",
"tried",
"twice",
"unless",
"upon",
"uses",
"very",
"wants",
"we'd",
"well",
"what's",
"where",
"wherein",
"while",
"whole",
"willing",
"won't",
"yet",
"you've",
"zero",
"above",
"after",
"all",
"along",
"am",
"another",
"anything",
"appear",
"around",
"associated",
"be",
"becoming",
"being",
"best",
"brief",
"came",
"cause",
"clearly",
"concerning",
"containing",
"course",
"did",
"doesn't",
"downwards",
"eight",
"entirely",
"ever",
"everywhere",
"far",
"followed",
"formerly",
"furthermore",
"gives",
"got",
"happens",
"haven't",
"help",
"hereafter",
"herself",
"hither",
"i'd",
"if",
"inc",
"inner",
"is",
"it's",
"keeps",
"last",
"least",
"like",
"looking",
"may",
"merely",
"mostly",
"name",
"necessary",
"nevertheless",
"nobody",
"normally",
"nowhere",
"oh",
"once",
"or",
"our",
"over",
"per",
"possible",
"quite",
"really",
"relatively",
"saw",
"secondly",
"seeming",
"sensible",
"several",
"since",
"somehow",
"somewhat",
"specify",
"sup",
"tell",
"thanks",
"the",
"then",
"thereby",
"these",
"they've",
"thoroughly",
"throughout",
"too",
"tries",
"two",
"unlikely",
"us",
"using",
"via",
"was",
"we'll",
"went",
"whatever",
"where's",
"whereupon",
"whither",
"whom",
"wish",
"wonder",
"you",
"your",
"according",
"afterwards",
"allow",
"already",
"among",
"any",
"anyway",
"appreciate",
"as",
"at",
"became",
"been",
"believe",
"better",
"but",
"can",
"causes",
"co",
"consequently",
"contains",
"currently",
"didn't",
"doing",
"during",
"either",
"especially",
"every",
"ex",
"few",
"following",
"forth",
"get",
"go",
"gotten",
"hardly",
"having",
"hence",
"hereby",
"hi",
"hopefully",
"i'll",
"ignored",
"indeed",
"insofar",
"isn't",
"its",
"kept",
"lately",
"less",
"liked",
"looks",
"maybe",
"might",
"much",
"namely",
"need",
"new",
"non",
"not",
"obviously",
"ok",
"one",
"other",
"ours",
"overall",
"perhaps",
"presumably",
"qv",
"reasonably",
"respectively",
"say",
"see",
"seems",
"sent",
"shall",
"six",
"someone",
"somewhere",
"specifying",
"sure",
"tends",
"thanx",
"their",
"thence",
"therefore",
"they",
"think",
"those",
"thru",
"took",
"truly",
"un",
"until",
"use",
"usually",
"viz",
"wasn't",
"we're",
"were",
"when",
"whereafter",
"wherever",
"who",
"whose",
"with",
"would",
"you'd",
"yours"
]